#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N QC_Trim
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=120GB,ncpus=21
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Create paths to required software or load modules"
module load fastqc/0.11.7
module load parallel/20191022 
module load multiqc/1.9 
module load python3/3.8.5
export PATH=$PATH:/g/data/pq84/bin/TrimGalore-0.6.6/ # trim galore wrapper for fastq and cutadapt
export PATH=$PATH:/home/588/jw1542/.local/bin # cutadapt_3.5 installed here

echo "---------------------------------------"
echo 'Change to working directory' 
cd /g/data/pq84/malaria/Pf_Malaysia/data/batch3

echo "---------------------------------------"
echo "Set environment variable"
QC_OUTDIR="/g/data/pq84/malaria/Pf_Malaysia/outputs/01_QC_Trim/fastqc/batch3"
TRIM_OUTDIR="/g/data/pq84/malaria/Pf_Malaysia/outputs/01_QC_Trim/trimmed_fastq/batch3"
mkdir $QC_OUTDIR
mkdir $TRIM_OUTDIR

echo "---------------------------------------"
echo "QC"
fastqc -t 20 -o $QC_OUTDIR *.fastq.gz
multiqc $QC_OUTDIR/. -o $QC_OUTDIR

echo "---------------------------------------"
echo "Trim"
parallel -j20 --xapply trim_galore --illumina --fastqc -o $TRIM_OUTDIR --paired ::: *1.fastq.gz ::: *2.fastq.gz

echo "---------------------------------------"
echo "QC on Trimmed"
multiqc $TRIM_OUTDIR/. -o $TRIM_OUTDIR

echo "---------------------------------------"
echo "Finished"