#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N moimix
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=128GB,ncpus=28
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
VCF="/g/data/pq84/malaria/Pf_Malaysia/data/malariaGEN/Pf7"
cd /g/data/pq84/malaria/Pf_Malaysia/outputs/06_Analyses

echo "---------------------------------------"
echo "Update VCF"
bcftools view $VCF/Pf3D7_subset.vcf.gz -M2 | bcftools view -f PASS - | bcftools view -e "MAC<2" -o moimix/Pf3D7_moimix_subset_2.vcf.gz 

echo "---------------------------------------"
echo "Create GDS file"
Rscript /g/data/pq84/malaria/Pf_Malaysia/scripts/06_Analyses/moimix/seqVCF2GDS_2.R

echo "---------------------------------------"
echo "Finished"