#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N Depth_R_wrangle
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=50GB,ncpus=11
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
cd /g/data/pq84/malaria/Pf_Malaysia/outputs/06_Analyses/Mapping

Rscript /g/data/pq84/malaria/Pf_Malaysia/scripts/06_Analyses/chromosome.R

echo "---------------------------------------"
echo "FINSIHED"