#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N vcf_to_bcf
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=16GB,ncpus=2
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12
FASTA="/g/data/pq84/malaria/Pf_Malaysia/data/ref_genomes/"
cd /g/data/pq84/malaria/Pf_Malaysia/outputs/06_Analyses

echo "---------------------------------------"
echo "VCF to BCF"
bcftools view moimix/Pf3D7_moimix_subset_2.vcf.gz | \
  sed 's/AD,Number=R/AD,Number=./' | \
  bcftools norm -m-any | \
  bcftools norm --check-ref w -f $FASTA/PlasmoDB-59_Pfalciparum3D7_Genome.fasta | \
  bcftools annotate -Ob -x ID -I +'%CHROM:%POS:%REF:%ALT:%ID' \
  > Pf3D7_subset_no_MOI.bcf

echo "---------------------------------------"
echo "FINISHED"
